#!/bin/bash

if [[ ! -f /home/solana/.secrets/validator-keypair.json || ! -f /home/solana/.secrets/validator-keypair.json ]]
then
  echo "Congratulations your Solana validator is almost ready !!!"
  echo "In order to complete the configuration, copy your validator-keypair and your vote-account-keypair in the following location."
  echo "/home/solana/.secrets/validator-keypair.json"
  echo "/home/solana/.secrets/vote-account-keypair.json"

  echo "If you don't have a validator-keypair and vote-account-keypair yet, refer to the official docs to generate one."
  echo "https://docs.solana.com/running-validator/validator-start#generate-identity"
  echo "https://docs.solana.com/running-validator/validator-start#create-authorized-withdrawer-account"
  echo "https://docs.solana.com/running-validator/validator-start#create-vote-account"
  echo "Caution!!! It is very important to keep your authorized-withdrawer keypair in a safe location. Do not copy it in this server."

  echo "When done start services:"
  echo "sudo systemctl start solana-sys-tuner.service"
  echo "sudo systemctl start solana-validator.service"
fi