---
all:
  children:
    testnet_validators:
      children:
        local:
          hosts:
            localhost:
              #any var from group vars:
              validator_homepage: ""
              validator_keybase: ""
            localhost_rpc:
              ansible_host: localhost
              force: true
              rpc_node: true
              solana_validator_service: started